### ISSUE TITLE
Candidate: Change the error message, etc.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#13]
Issue 1. Change "Please fill the existing candidate details before adding a new candidate"
    TO
     "Please fill ALL the details of the selected candidate before adding a new candidate"

Issue 2. Delete button is still enabled soon after deleting a candidate even if no other candidate is selected. It should be disabled when no other candidate is selected. 

Issue 3. Add tool tips for + and - buttons of candidate.

Issue 4: When a date is selected, i.e. when candidate details are listed, change the window title to 'List of Candidates for <mm/dd/yyyy>

**Comment by PratibhaSawargi** [comment]
I will work on it.

**Comment by PratibhaSawargi** [comment]
Issue resolved,Please verify.

**Comment by srilatha-sriram** [comment]
4 issues were reported. Can u clarify which issue is resolved. If all are done, you should clearly mention that.

**Comment by PratibhaSawargi** [comment]
Issue 1,issue 3,issue 4 are resolved. Issue 2 i will fix it soon.

**Comment by srilatha-sriram** [comment]
You should assign to me as request for verification only after all the issues are resolved.

**Comment by PratibhaSawargi** [comment]
Okay. I will take care.

**Comment by PratibhaSawargi** [comment]
Issue 1 : Changed the informativeText.
Issue 2 : Delete button is disabled when no other candidate is selected.
Issue 3. Added tool tips for + and - buttons of candidate.
Issue 4: When a date is selected,  changed the window title to 'List of Candidates.
All issues are fixed. Please verify and let me know if any changes required.

**Comment by srilatha-sriram** [comment]
Issue 2 & 3 are still not fixed. Please make sure you CHECK/TEST THOROUGHLY before sending for verification.

**Comment by PratibhaSawargi** [comment]
Yesterday itself i have resolved issue2 and issue 3. Because of some conflict that is not reflecting in code.Now i am checking.

**Comment by PratibhaSawargi** [comment]
Issue 2 : Delete button is disabled when no other candidate is selected in tableview.

**Comment by srilatha-sriram** [comment]
Verified. Closing.

**Comment by PratibhaSawargi** [comment]
In tableview when we add a empty candidate, after selecting that candidate it was taking to feedback controller.This issue is now fixed.
